window.AppConfig = {
    apiBase: '/api',
    refreshIntervalMs: 5000,
    chartRefreshIntervalMs: 60000,

    view: {
        centerXRatio: 0.50,
        centerYRatio: 0.45,
        radiusWRatio: 0.32,
        radiusHRatio: 0.38,
        canvasHeightPx: 500,
        waterYRatio: 0.75,
        waterHeightRatio: 0.22,
        bucketCountFallback: 20,
        spokeCount: 12,
        axleRadiusRatio: 0.12,
        hoverRadiusPx: 25,
        groundHeightPx: 15,
        dropLifeSec: 1.5,
        dropGravity: 0.15,
        flowArrowCount: 5,
        starCount: 30,
        speedOptions: [1, 2, 5, 10],
        defaultSpeed: 1,
    },

    particles: {
        workerScript: 'js/particle-worker.js',
        workerCount: 120,
        fallbackCount: 80,
        addDropCount: 2,
        dropTriggerProb: 0.15,
        minSpeed: 1.0,
        minSize: 1.0,
        maxSize: 4.0,
        minAlpha: 0.3,
        maxAlpha: 0.8,
    },

    colors: {
        bgStart: '#0d1b2a',
        bgMid: '#1b2838',
        bgEnd: '#1a3a4a',
        waterStart: 'rgba(30, 136, 229, 0.6)',
        waterMid: 'rgba(21, 101, 192, 0.7)',
        waterEnd: 'rgba(13, 71, 161, 0.9)',
        particle: 'rgba(129, 212, 250, ',
        drop: 'rgba(100, 181, 246, ',
        wheelOuter: '#8d6e63',
        wheelInner: '#6d4c41',
        wheelInnerRing: '#795548',
        wheelSpokes: '#6d4c41',
        bucketStart: '#a1887f',
        bucketEnd: '#6d4c41',
        bucketHoverStart: '#bcaaa4',
        bucketHoverEnd: '#8d6e63',
        bucketWater: 'rgba(30, 136, 229, 0.75)',
        bucketWaterShine: 'rgba(129, 212, 250, 0.6)',
        supports: '#5d4037',
        supportsStroke: '#3e2723',
        supportsLight: '#6d4c41',
        ground: '#2d1f12',
        groundLight: '#3e2723',
        good: '#66bb6a',
        warning: '#ffb74d',
        danger: '#ef5350',
        info: '#4fc3f7',
    },

    panel: {
        chartHeightPx: 200,
        padL: 45,
        padR: 15,
        padT: 15,
        padB: 30,
        alertLimit: 20,
        optHistoryLimit: 10,
        defaultChartRangeHours: 24,
        chartRangeOptions: [1, 6, 24, 168],
        optimizationTimeoutMs: 35000,
    },

    scheduler: {
        defaultTargetM3: 500,
        defaultDeadlineHours: 24,
        defaultElectricityPrice: 0.85,
        minTargetM3: 10,
        maxTargetM3: 100000,
        minDeadlineHours: 1,
        maxDeadlineHours: 168,
    },

    forecasting: {
        forecastHorizonDays: 30,
        confidenceLevel: 0.85,
        targetSubmergenceRatio: 0.35,
        chartHeightPx: 220,
        padL: 50,
        padR: 20,
        padT: 20,
        padB: 40,
        colors: {
            historical: '#4fc3f7',
            forecast: '#ab47bc',
            upperBound: 'rgba(171, 71, 188, 0.25)',
            lowerBound: 'rgba(171, 71, 188, 0.15)',
            seasonWinter: '#64b5f6',
            seasonSpring: '#66bb6a',
            seasonSummer: '#ef5350',
            seasonAutumn: '#ffa726',
        },
    },

    efficiency: {
        defaultLifespanYears: 15,
        defaultMaintenanceRate: 0.04,
        defaultElectricityPrice: 0.85,
        chartHeightPx: 180,
    },

    build: {
        canvas: { width: 760, height: 520 },
        diameter: { min: 2.0, max: 15.0, step: 0.1 },
        buckets: { min: 6, max: 48, step: 1 },
        spokes: { min: 4, max: 24, step: 2 },
        capacity: { min: 0.01, max: 0.5, step: 0.005 },
        height: { min: 0, max: 8.0, step: 0.05 },
        flow: { min: 0.2, max: 5.0, step: 0.1 },
        drop: { min: 0.5, max: 8.0, step: 0.1 },
        defaultDiameter: 6.0,
        defaultBuckets: 16,
        defaultCapacity: 0.06,
        defaultSpokes: 10,
        defaultMaterial: '杉木',
        defaultHeight: 2.7,
        defaultFlow: 1.5,
        defaultDrop: 2.0,
        simulationDebounceMs: 200,
        animationFps: 60,
        stressLimitRatio: 0.85,
        stabilityMinRatio: 0.6,
        materials: [
            { name: '楠木', density: 0.61, color: '#6B4423' },
            { name: '杉木', density: 0.38, color: '#8B7355' },
            { name: '柏木', density: 0.58, color: '#5C4033' },
            { name: '松木', density: 0.45, color: '#A0826D' },
            { name: '竹制', density: 0.65, color: '#7CB342' },
            { name: '铸铁', density: 7.20, color: '#424242' },
        ],
        parts: [
            { id: 'support_reinforce', icon: '🏛️', name: '加固支架', desc: '增强底座稳定性 +15%', category: 'structure', effect: { stabilityBonus: 0.15 } },
            { id: 'main_axle_steel', icon: '⚙️', name: '钢制主轴', desc: '减少摩擦损耗 -8%', category: 'mech', effect: { mechLossReduction: 0.08 } },
            { id: 'reinforced_spokes', icon: '🔧', name: '加固辐条', desc: '允许更大轮径 +2m 上限', category: 'structure', effect: { diameterMaxBonus: 2.0 } },
            { id: 'big_bucket', icon: '🪣', name: '加大水斗', desc: '单斗容量 +50%', category: 'water', effect: { capacityMultiplier: 1.5 } },
            { id: 'outer_ring_giant', icon: '⭕', name: '巨轮外框', desc: '轮径上限 +4m', category: 'structure', effect: { diameterMaxBonus: 4.0 } },
            { id: 'chain_drive', icon: '🔗', name: '传动链系统', desc: '传导效率 +10%', category: 'mech', effect: { mechEffBonus: 0.10 } },
        ],
    },

    tabs: {
        order: ['monitor', 'scheduler', 'forecast', 'efficiency', 'build'],
        labels: {
            monitor: '📊 监测中心',
            scheduler: '🌾 灌溉调度',
            forecast: '🌊 水位预测',
            efficiency: '⚖️ 能效对比',
            build: '🏗️ 虚拟建造',
        },
    },
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = window.AppConfig;
}
